# Generated by Django 3.1.5 on 2021-02-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastresultmodel',
            name='prodict_median',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='forecastresultmodel',
            name='retest_median',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='forecastresultmodel',
            name='delta',
            field=models.FloatField(default=0),
        ),
    ]
